name: CI

on: push

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout # copy code to runner
        uses: actions/checkout@v3

      - name: setup python. # setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install flake8 # install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8 # run flake8
        run: |
          flake8 app.py
          
