name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  linting:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['3.9', '3.10']

    steps:
      - name: code checkout # copy code to runner
        uses: actions/checkout@v3

      - name: setup python # setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}   # use matrix version
          
      - name: install flake8 # install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8 # run flake8
        run: |
          flake8 app.py

  testing:
    needs: linting
    runs-on: ubuntu-latest

    steps:
      - name: code checkout # copy code to runner
        uses: actions/checkout@v3

      - name: setup python # setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: run unit tests # run unit tests
        run: |
          python -m unittest discover